# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.5.2
_src_path: gh:oca/oca-addons-repo-template
ci: Travis
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups:
- purchase_cancel_reason
- purchase_cancel_confirm
- purchase_order_type
- purchase_quick
repo_description: 'TODO: add repo description.'
repo_name: purchase-workflow
repo_slug: purchase-workflow
repo_website: https://github.com/OCA/purchase-workflow
travis_apt_packages: []
travis_apt_sources: []
