# -*- coding: utf-8 -*-
#
#
#    Authors: Alexandre Fayolle, Leonardo Pistone
#    Copyright 2015 Camptocamp SA
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#

from openerp.tests import common

from .helper import AmendmentMixin


class TestResupplyAmendment(common.TransactionCase, AmendmentMixin):
    def setUp(self):
        super(TestResupplyAmendment, self).setUp()
        ref = self.env.ref
        self.amendment_model = self.env['purchase.order.amendment']
        self.purchase_model = self.env['purchase.order']
        self.purchase_line_model = self.env['purchase.order.line']
        self.partner1 = ref('base.res_partner_2')
        self.product2 = ref('product.product_product_9')
        self.product3 = ref('product.product_product_11')
        self.location_stock = self.env.ref('stock.stock_location_stock')
        self.purchase_pricelist = self.env.ref('purchase.list0')
        order_point = self.env['stock.warehouse.orderpoint']
        op_data = {'warehouse_id': ref('stock.warehouse0').id,
                   'location_id': ref('stock.stock_location_stock').id,
                   'product_min_qty': 80,
                   'product_max_qty': 123,
                   }
        self.order_points = order_point
        for product in (self.product2,
                        self.product3):
            product.route_ids = ref('purchase.route_warehouse0_buy')
            product.seller_ids[0].name = self.partner1
            op_data['product_id'] = product.id
            self.order_points |= order_point.create(op_data)
        self.env['procurement.order'].run_scheduler()
        self.purchase = self.order_points.mapped('procurement_ids.purchase_id')
        self.purchase.invoice_method = 'manual'
        self.purchase.signal_workflow('purchase_confirm')

    def test_po(self):
        self.assertEqual(len(self.purchase), 1)
        self.assert_moves([
            (self.product2, 101, 'assigned'),
            (self.product3, 97, 'assigned'),
        ])
        self.assert_purchase_lines([
            (self.product2, 101, 'confirmed'),
            (self.product3, 97, 'confirmed'),
        ])

    def test_not_received_reduce_quantity(self):
        """Given I have a confirmed PO generated by a procurement
        And I haven't received anything
        When I amend it to reduce the quantity of a line
        Then the order line is split with states "cancel" and "confirmed"
        And the stock move is split with states "cancel" and "assigned"

        """
        amendment = self.amend()
        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'original_qty': 101,
             'new_qty': 101,
             'state': 'assigned'},
            {'product_id': self.product3,
             'original_qty': 97,
             'new_qty': 97,
             'state': 'assigned'},
        ], amendment.item_ids)
        self.amend_product(amendment, self.product2, 30)
        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'original_qty': 101,
             'new_qty': 30,
             'state': 'assigned'},
            {'product_id': self.product3,
             'original_qty': 97,
             'new_qty': 97,
             'state': 'assigned'},
        ], amendment.item_ids)

        amendment.do_amendment()

        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'product_qty': 71.,
             'state': 'cancel'},
            {'product_id': self.product2,
             'product_qty': 30.,
             'state': 'confirmed'},
            {'product_id': self.product3,
             'product_qty': 97.,
             'state': 'confirmed'},
        ], self.purchase.order_line)

        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'product_qty': 71,
             'state': 'cancel'},
            {'product_id': self.product2,
             'product_qty': 30,
             'state': 'assigned'},
            {'product_id': self.product3,
             'product_qty': 97,
             'state': 'assigned'},
        ], self.purchase.mapped('picking_ids.move_lines'))

        self.assertEqual(self.purchase.state, 'approved')

    def test_ship_and_cancel_part(self):
        """Given I have a confirmed PO generated by a procurement
        And I haven't received anything
        When I amend it to reduce the quantity of a line
        Then the order line is split with states "cancel", "confirmed"
        And the stock move is split with states "cancel", "done", "assigned"

        """
        self.ship([(self.product2, 51),
                   (self.product3, 0),
                   ])
        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'product_qty': 51,
             'state': 'done'},
            {'product_id': self.product2,
             'product_qty': 50,
             'state': 'assigned'},
            {'product_id': self.product3,
             'product_qty': 97,
             'state': 'assigned'},
        ], self.purchase.mapped('picking_ids.move_lines'))

        amendment = self.amend()
        self.amend_product(amendment, self.product2, 30)
        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'original_qty': 51,
             'new_qty': 51,
             'state': 'done'},
            {'product_id': self.product2,
             'original_qty': 50,
             'new_qty': 30,
             'state': 'assigned'},
            {'product_id': self.product3,
             'original_qty': 97,
             'new_qty': 97,
             'state': 'assigned'},
        ], amendment.item_ids)

        amendment.do_amendment()

        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'product_qty': 20.,
             'state': 'cancel'},
            {'product_id': self.product2,
             'product_qty': 81.,
             'state': 'confirmed'},
            {'product_id': self.product3,
             'product_qty': 97.,
             'state': 'confirmed'},
        ], self.purchase.order_line)

        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'product_qty': 51.,
             'state': u'done'},
            {'product_id': self.product2,
             'product_qty': 20.,
             'state': u'cancel'},
            {'product_id': self.product2,
             'product_qty': 30.,
             'state': u'assigned'},
            {'product_id': self.product3,
             'product_qty': 97.,
             'state': u'assigned'},
        ], self.purchase.mapped('picking_ids.move_lines'))

        self.assertEqual(self.purchase.state, 'approved')

    def test_cancel_one_line(self):
        """Given I have a confirmed PO generated by a procurement
        And I haven't received anything
        When I amend it to reduce the quantity of a line to zero
        Then the order line has state "cancel"
        And the stock move has state "cancel"

        """
        amendment = self.amend()
        self.amend_product(amendment, self.product2, 0.)
        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'original_qty': 101.,
             'new_qty': 0.,
             'state': 'assigned'},
            {'product_id': self.product3,
             'original_qty': 97.,
             'new_qty': 97.,
             'state': 'assigned'},
        ], amendment.item_ids)

        amendment.do_amendment()

        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'product_qty': 101.,
             'state': 'cancel'},
            {'product_id': self.product3,
             'product_qty': 97.,
             'state': 'confirmed'},
        ], self.purchase.order_line)

        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'product_qty': 101.,
             'state': u'cancel'},
            {'product_id': self.product3,
             'product_qty': 97.,
             'state': u'assigned'},
        ], self.purchase.mapped('picking_ids.move_lines'))

        self.assertEqual(self.purchase.state, 'approved')

    def test_amend_more(self):
        """Given I have a confirmed PO generated by a procurement
        And I haven't received anything
        When I amend it to increase the quantity of a line
        Then the order line is split with states "confirmed" and "confirmed"
        And the stock move is split with states "confirmed" and "assigned"

        """
        amendment = self.amend()
        self.amend_product(amendment, self.product2, 150.)
        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'original_qty': 101.,
             'new_qty': 150.,
             'state': 'assigned'},
            {'product_id': self.product3,
             'original_qty': 97.,
             'new_qty': 97.,
             'state': 'assigned'},
        ], amendment.item_ids)

        amendment.do_amendment()

        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'product_qty': 150.,
             'state': 'confirmed'},
            {'product_id': self.product3,
             'product_qty': 97.,
             'state': 'confirmed'},
        ], self.purchase.order_line)

        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'product_qty': 150.,
             'state': u'assigned'},
            {'product_id': self.product3,
             'product_qty': 97.,
             'state': u'assigned'},
        ], self.purchase.mapped('picking_ids.move_lines'))

        self.assertEqual(self.purchase.state, 'approved')

    def test_ship_amend_more(self):
        self.ship([(self.product2, 20),
                   (self.product3, 0),
                   ])
        amendment = self.amend()
        self.amend_product(amendment, self.product2, 150.)
        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'original_qty': 20.,
             'new_qty': 20.,
             'state': 'done'},
            {'product_id': self.product2,
             'original_qty': 81.,
             'new_qty': 150.,
             'state': 'assigned'},
            {'product_id': self.product3,
             'original_qty': 97.,
             'new_qty': 97.,
             'state': 'assigned'},
        ], amendment.item_ids)

        amendment.do_amendment()

        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'product_qty': 170.,
             'state': 'confirmed'},
            {'product_id': self.product3,
             'product_qty': 97.,
             'state': 'confirmed'},
        ], self.purchase.order_line)

        self.assertRecordsetEqual([
            {'product_id': self.product2,
             'product_qty': 20.,
             'state': u'done'},
            {'product_id': self.product2,
             'product_qty': 150.,
             'state': u'assigned'},
            {'product_id': self.product3,
             'product_qty': 97.,
             'state': u'assigned'},
        ], self.purchase.mapped('picking_ids.move_lines'))

        self.assertEqual(self.purchase.state, 'approved')
