# -*- coding: utf-8 -*-
##############################################################################
#
#    Author: Nicolas Bessi
#    Copyright 2013 Camptocamp SA
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
from openerp import netsvc
from openerp.osv import orm, fields


class sale_order_line(orm.Model):
    """Pass agreement PO into state confirmed when SO is confirmed"""

    _inherit = "sale.order.line"

    def button_confirm(self, cr, uid, ids, context=None):
        """Override confirmation of request of cotation to support LTA

        Related PO generated by agreement source line will be pased to state confirm.

        """
        po_line_model = self.pool['purchase.order.line']
        result = super(sale_order_line, self).button_confirm(cr, uid, ids, context=context)
        lines = self.browse(cr, uid, ids, context=context)
        source_ids = [x.logistic_requisition_source_id.id for x in lines
                           if x.logistic_requisition_source_id]
        po_line_ids = po_line_model.search(cr, uid,
                                           [('lr_source_line_id', 'in', source_ids)],
                                           context=context)
        po_lines = po_line_model.read(cr, uid, po_line_ids, ['order_id'], load='_classic_write')
        po_ids = set(x['order_id'] for x in po_lines)
        wf_service = netsvc.LocalService("workflow")
        for po_id in po_ids:
            wf_service.trg_validate(uid, 'purchase.order', po_id, 'draft_po', cr)
            wf_service.trg_validate(uid, 'purchase.order', po_id, 'purchase_confirm', cr)
        return result
