# Copyright 2025 ACSONE SA/NV
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import fields, models


class StockRoute(models.Model):
    _inherit = "stock.route"

    purchase_tag_ids = fields.Many2many(
        comodel_name="purchase.tag",
        relation="stock_route_purchase_tag_rel",
        column1="stock_route_id",
        column2="tag_id",
        string="Purchase Tags",
        help="Fill in this with purchase tags you want appear "
        "on purchase orders generated by this route",
    )
