# Copyright 2020 ACSONE SA/NV
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Purchase Sale Amendment",
    "summary": """
        Allows to amend a purchase generated by sale""",
    "version": "13.0.1.0.0",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV,Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/purchase-workflow",
    "maintainers": ["rousseldenis"],
    "depends": ["sale_procurement_amendment", "purchase_stock"],
}
