[project]
name = "odoo-addons-oca-purchase-workflow"
version = "19.0.20251219.0"
dependencies = [
    "odoo-addon-purchase_order_owner==19.0.*",
    "odoo-addon-purchase_order_weight_volume==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
