[project]
name = "odoo-addons-oca-purchase-workflow"
version = "18.0.20250606.0"
dependencies = [
    "odoo-addon-procurement_purchase_no_grouping==18.0.*",
    "odoo-addon-purchase_advance_payment==18.0.*",
    "odoo-addon-purchase_all_shipments==18.0.*",
    "odoo-addon-purchase_analytic_global==18.0.*",
    "odoo-addon-purchase_blanket_order==18.0.*",
    "odoo-addon-purchase_cancel_reason==18.0.*",
    "odoo-addon-purchase_commercial_partner==18.0.*",
    "odoo-addon-purchase_delivery_split_date==18.0.*",
    "odoo-addon-purchase_deposit==18.0.*",
    "odoo-addon-purchase_exception==18.0.*",
    "odoo-addon-purchase_fop_shipping==18.0.*",
    "odoo-addon-purchase_force_invoiced==18.0.*",
    "odoo-addon-purchase_invoice_plan==18.0.*",
    "odoo-addon-purchase_last_price_info==18.0.*",
    "odoo-addon-purchase_manual_currency==18.0.*",
    "odoo-addon-purchase_manual_delivery==18.0.*",
    "odoo-addon-purchase_open_qty==18.0.*",
    "odoo-addon-purchase_order_archive==18.0.*",
    "odoo-addon-purchase_order_general_discount==18.0.*",
    "odoo-addon-purchase_order_line_menu==18.0.*",
    "odoo-addon-purchase_order_qty_change_no_recompute==18.0.*",
    "odoo-addon-purchase_order_secondary_unit==18.0.*",
    "odoo-addon-purchase_order_supplierinfo_update==18.0.*",
    "odoo-addon-purchase_order_type==18.0.*",
    "odoo-addon-purchase_order_type_dashboard==18.0.*",
    "odoo-addon-purchase_order_uninvoiced_amount==18.0.*",
    "odoo-addon-purchase_partner_incoterm==18.0.*",
    "odoo-addon-purchase_partner_selectable_option==18.0.*",
    "odoo-addon-purchase_request==18.0.*",
    "odoo-addon-purchase_request_department==18.0.*",
    "odoo-addon-purchase_request_tier_validation==18.0.*",
    "odoo-addon-purchase_request_type==18.0.*",
    "odoo-addon-purchase_requisition_line_description==18.0.*",
    "odoo-addon-purchase_tag==18.0.*",
    "odoo-addon-purchase_tier_validation==18.0.*",
    "odoo-addon-sale_purchase_force_vendor==18.0.*",
    "odoo-addon-supplier_calendar==18.0.*",
    "odoo-addon-vendor_transport_lead_time==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
